# deploy.yml

name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Deploys when you push to the 'main' branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use a recent LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
        env:
          CI: false # Prevents treating warnings as errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # The directory the build output is in